### ISSUE TITLE
Allow usage of external tokenizers

### ISSUE THREAD

**Issue by drahnr** [bminixhofer/nlprule#13]
Extracting a `Trait` to be used by external tokenizers i.e. https://github.com/guillaume-be/rust-bert would be very nice!

**Comment by bminixhofer** [comment]
Hi, what's your use case for this?

The problem here is that the LanguageTool rules are highly dependent on the "right" tokenizer being used. There are for example rules which need quotation marks to be treated as a separate token and words with dashes as one token.

Also, what's perhaps a bit misleadingly called the `Tokenizer` (I'm open to suggestions for a different name!) also does chunking and part-of-speech tagging as mentioned at https://docs.rs/nlprule/0.3.0/nlprule/tokenizer/index.html. So it would not be easy to replace and I don't really see a reason to.

**Comment by drahnr** [comment]
I wasn't aware the tokenizer is tangled into some other requirements, in that case, ignore this.
