### ISSUE TITLE
Questions about adding a new language

### ISSUE THREAD

**Issue by chris4540** [bminixhofer/nlprule#14]
Hi,

I would like to ask if it is easy to add a new language?

If so, are there any good reference to guess how to add it?

Best,
Chris

**Comment by bminixhofer** [comment]
Hi, thanks for the issue! Which language are you interested in?

It is not trivial to add a new language because there is some language-specific code in LanguageTool which has to be adapted (e. g. subtly different tokenization or language specific heuristics).

The main bottleneck for adding a language at the moment is documentation since you would likely have to make some changes in the internals of NLPRule and they are not well documented right now.

That said, I am currently working on support for Spanish and making a guide for how to add new languages. That should make it much easier to do so.

**Comment by neoscopio** [comment]
Hi, I'll be interested in contributing work to add Portuguese (pt_PT) language. I'll be waiting for some start-up guide. Thanks for your work.

**Comment by bminixhofer** [comment]
Thanks for letting me know! Yes that got delayed a bit because there's been lots of other improvements recently (#22, #24, multiword tagging). It is on my radar but it will take some more time.

**Comment by bminixhofer** [comment]
This is now tracked in #46.
