### ISSUE TITLE
Craft releases frequently

### ISSUE THREAD

**Issue by drahnr** [bminixhofer/nlprule#25]
It's significantly easier for other projects to adapt on small changes, rather than rare yet large changesets.

In this case I would love to craft a cargo spellcheck release, but I'd be in need of the current `master`, and in a perfect world the changes of #24

Thanks

I really appreciate the work you do here!

**Comment by bminixhofer** [comment]
Thanks! 

I agree. There's been lots of useful changes recently and I overlooked releasing a bit. I'm not sure a fixed release schedule makes sense - probably not - but more frequent releases are definitely good. 

This time it's a bit awkward because Spanish support is merged (#16) but not fully tested and benchmarked yet. I should've held off on merging that a bit longer and released instead. I'll try keeping `master` release-ready at all times in the future to avoid such things.

So there is still some cleaning up to do (Spanish will just get an "experimental" flag for now) but the next release will include #24 and be this week.

**Comment by bminixhofer** [comment]
It took some patches to get everything right but https://github.com/bminixhofer/nlprule/releases/tag/0.4.3 is now the latest release. I'm closing this issue with the intention to release more frequently.

**Comment by drahnr** [comment]
Thanks!
