### ISSUE TITLE
Usability of the rules API degraded from 0.4.6 to 0.5.1

### ISSUE THREAD

**Issue by drahnr** [bminixhofer/nlprule#57]
Updating nlprule from 0.4.6 to 0.5.1 due to #53 is not as smooth as anticipated.

The whole idea of having a straight forward iterator over the individual rules, filtering and collecting them as needed is gone.

The API of `select` is rather awkward to use, it seems like a stripped down version of (the previously working) `.into_iter().filter(|| -> bool {})` but without the possibility to specify a closure. There is no alternative based on `rules()` since the `Rule` is not `Clone`. Operating on the mutable slice instead is non-idiomatic.

Would you consider reverting this? It seems more hassle without any(or, I don't see it) gain.

Thanks!

**Comment by bminixhofer** [comment]
Hi, sorry, that was not intended: The select API is just part of a streamlined version of rule identifiers (the `id` field; previously this was a String containing group id and rule index which wasn't necessarily unique between all rules; now it is unique and the `rule_group` and `category` fields on the rule aren't necessary anymore because they're part of the `Index`. 

The API to match (`select`, `select_mut`) is just a nice addition that's mainly convenient for Python, although I'd see it being useful in Rust too.) So the select API is purely an addition. 

The issue you're having is because the `RulesOptions` are part of the `Rules` now making it not possible to `.collect` into `Rules` anymore. The `RulesOptions` are leftover from trying a config upon initialization of the `Rules`. As it stands now (with spellchecking a separate struct and the ability to disable / enable rules in the select API) this doesn't make sense anymore anyway so I'll remove the `RulesOptions` and add back the `FromIterator` impl. I'll fix that today.
