### ISSUE TITLE
Support distinguishing between grammar and style errors

### ISSUE THREAD

**Issue by ssokolow** [bminixhofer/nlprule#83]
LanguageTool's web demo highlights grammar errors in yellow and style errors in blue.

It'd be nice to have access to that information in suggestions without having to take `s.source` and look it up in an external mapping table, similar to how, back in the GTK+ 2.x era with PyGTK and the Glade GUI builder, I had to do a second, independent parse of the XML UI definition with a normal DOM parser to recover certain bits of metadata I needed and which it stored but didn't expose through GtkBuilder API.

**Comment by bminixhofer** [comment]
Parsing the category is easy from `s.source` by taking the part up to the first `/`. You can have a color table mapping category names to colors. I don't see how this could be improved. What's your concrete suggestion for a change?

I guess the `s.source` might better be implemented as an [Index](https://docs.rs/nlprule/latest/nlprule/rule/id/struct.Index.html) instead of a string, is that what you were expecting?

**Comment by ssokolow** [comment]
I was thinking something like an enum (from the `enum` standard library module, in Python's case) with one variant for each category class, so you don't have to:

1. Know that it's correct/safe to parse the category by taking the part up to the first `/`
2. Write that boilerplate
3. Manually derive a list of sources from the list of sources

**Comment by bminixhofer** [comment]
OK, I see your point. The problem is that the categories are dynamic. They are determined by the binary and may vary across binaries. I'm fairly sure they vary across languages in LanguageTool as well. So having a closed set of categories is not possible, unless a wildcard "Other(String)" category is included. But in general I want to keep the code as independent of the data in the binaries as possible so this would also not be worth the complexity IMO.
